spin_manifest_version = 2

[application]
name = "dev-tools"
description = "A set of tools"
version = "0.3.0"

[[trigger.http]]
route = "/api/..."
component = "api"

[component.api]
source = "api/target/wasm32-wasi/release/api.wasm"

[component.api.build]
workdir = "api"
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "fs"

[component.fs]
source = "modules/spin_static_fs.wasm"
files = [ { source="web/dist", destination="/" } ]
environment = { FALLBACK_PATH = "index.html" }

[component.fs.build]
workdir = "web"
command = "npm run build"
watch = ["src/**/*.tsx", "src/**/*.css", "package.json"]
