spin_manifest_version = "1"
authors = ["Fabien D. <fabien@myprod.net>"]
description = "A set of tools"
name = "dev-tools"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "dev-tools"
source = "target/wasm32-wasi/release/dev_tools.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
